### ISSUE TITLE
BUG: When a user is sharing their screen and leaves the room, the screen is still being shown to other participants even though the user has left the room.

### ISSUE THREAD

**Issue by fpyoung** [montevideo-tech/hybrid-meetup-platform#174]
When a user is sharing their screen in a room and then leaves the room, the screen is still being shown to other participants even though the user has left the room. This can cause confusion and disrupt the meeting flow as participants may still think that the user is still present in the room.

Steps to reproduce:

1- Have a user join a room and share their screen.
2- Have the user leave the room.
Observe that the screen is still being shown to other participants.
Expected result:
When a user leaves the room while sharing their screen, the screen should stop being shown to other participants.

**Comment by fpyoung** [comment]
@pollingerMaxi this is the issue we spoke about on the hallway.

**Comment by mpollingerQualabs** [comment]
@yulianag-qualabs have you tried stopping the screen share when onDismount of the component?
Also, have you tried with the `window.onbeforeunload` event? For this one, make sure to add the `event.preventDefault();`

**Comment by mpollingerQualabs** [comment]
@fyoungqualabs @yulianag-qualabs this issue is solved in #178 , right?

**Comment by fpyoung** [comment]
We will revisit this on this sprint since this issue wasn't solved.
